### ISSUE TITLE
Decompose, RemoveOverlap and DecomposeRemoveOverlap as 3 steps?

### ISSUE THREAD

**Issue by davelab6** [signalwerk/fontstep#1]
In https://github.com/signalwerk/fontstep/blob/master/fontstep.py#L169-L174 there is a combined DecomposeRemoveOverlap action as 'Decompose' - but for filesize reasons its common to want to keep composite glyphs but remove overlap, so I suggest providing Decompose, RemoveOverlap and DecomposeRemoveOverlap as 3 steps

**Comment by signalwerk** [comment]
Sounds nice and logical! 100% agreement here and I'm more than happy to accept patches. ★

**Comment by signalwerk** [comment]
I hope this works for you. :pray:
I split it up in 3 steps as suggested by you: decompose, removeOverlap, decomposeRemoveOverlap
